-- MySQL Script generated by MySQL Workbench
-- Tue Aug  1 19:51:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(255) NULL,
  `privilegio` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctores` (
  `doctorId` INT NOT NULL AUTO_INCREMENT,
  `nombreDoctor` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `cedulaprofesional` VARCHAR(45) NULL,
  PRIMARY KEY (`doctorId`, `usuarios_idusuarios`),
  INDEX `fk_doctores_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_doctores_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `idpacientes` INT NOT NULL AUTO_INCREMENT,
  `nombrepacientes` VARCHAR(45) NULL,
  `doctores_doctorId` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `RFCpaciente` VARCHAR(45) NULL,
  `direccion` BLOB NULL,
  `alegias` BLOB NULL,
  PRIMARY KEY (`idpacientes`, `doctores_doctorId`, `usuarios_idusuarios`),
  INDEX `fk_pacientes_doctores_idx` (`doctores_doctorId` ASC) VISIBLE,
  INDEX `fk_pacientes_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_pacientes_doctores`
    FOREIGN KEY (`doctores_doctorId`)
    REFERENCES `mydb`.`doctores` (`doctorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asistentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asistentes` (
  `idasistentes` INT NOT NULL AUTO_INCREMENT,
  `nombreAsistente` VARCHAR(45) NULL,
  `doctores_doctorId` INT NOT NULL,
  `usuarios_idusuarios1` INT NOT NULL,
  PRIMARY KEY (`idasistentes`, `doctores_doctorId`, `usuarios_idusuarios1`),
  INDEX `fk_asistentes_doctores1_idx` (`doctores_doctorId` ASC) VISIBLE,
  INDEX `fk_asistentes_usuarios2_idx` (`usuarios_idusuarios1` ASC) VISIBLE,
  CONSTRAINT `fk_asistentes_doctores1`
    FOREIGN KEY (`doctores_doctorId`)
    REFERENCES `mydb`.`doctores` (`doctorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistentes_usuarios2`
    FOREIGN KEY (`usuarios_idusuarios1`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`expedientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`expedientes` (
  `expedienteID` INT NOT NULL AUTO_INCREMENT,
  `pacientes_idpacientes` INT NOT NULL,
  `padecimiento` VARCHAR(45) NULL,
  `tratamiento` VARCHAR(45) NULL,
  `antecedentes` VARCHAR(45) NULL,
  PRIMARY KEY (`expedienteID`, `pacientes_idpacientes`),
  INDEX `fk_expedientes_pacientes1_idx` (`pacientes_idpacientes` ASC) VISIBLE,
  CONSTRAINT `fk_expedientes_pacientes1`
    FOREIGN KEY (`pacientes_idpacientes`)
    REFERENCES `mydb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`citas` (
  `idcitas` INT NOT NULL AUTO_INCREMENT,
  `fechacitas` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `pacientes_idpacientes` INT NOT NULL,
  `doctores_doctorId` INT NOT NULL,
  PRIMARY KEY (`idcitas`, `pacientes_idpacientes`, `doctores_doctorId`),
  INDEX `fk_citas_pacientes1_idx` (`pacientes_idpacientes` ASC) VISIBLE,
  INDEX `fk_citas_doctores1_idx` (`doctores_doctorId` ASC) VISIBLE,
  CONSTRAINT `fk_citas_pacientes1`
    FOREIGN KEY (`pacientes_idpacientes`)
    REFERENCES `mydb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_doctores1`
    FOREIGN KEY (`doctores_doctorId`)
    REFERENCES `mydb`.`doctores` (`doctorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `idservicios` INT NOT NULL AUTO_INCREMENT,
  `servicio` VARCHAR(45) NULL,
  `costo` DOUBLE NULL,
  `doctores_doctorId` INT NOT NULL,
  PRIMARY KEY (`idservicios`, `doctores_doctorId`),
  INDEX `fk_servicios_doctores1_idx` (`doctores_doctorId` ASC) VISIBLE,
  CONSTRAINT `fk_servicios_doctores1`
    FOREIGN KEY (`doctores_doctorId`)
    REFERENCES `mydb`.`doctores` (`doctorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consultorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consultorios` (
  `idconsultorios` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `RFC` VARCHAR(45) NULL,
  `folio` VARCHAR(45) NULL,
  `servicios_idservicios` INT NOT NULL,
  `servicios_doctores_doctorId` INT NOT NULL,
  PRIMARY KEY (`idconsultorios`, `servicios_idservicios`, `servicios_doctores_doctorId`),
  INDEX `fk_consultorios_servicios1_idx` (`servicios_idservicios` ASC, `servicios_doctores_doctorId` ASC) VISIBLE,
  CONSTRAINT `fk_consultorios_servicios1`
    FOREIGN KEY (`servicios_idservicios` , `servicios_doctores_doctorId`)
    REFERENCES `mydb`.`servicios` (`idservicios` , `doctores_doctorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagos` (
  `idpagos` INT NOT NULL AUTO_INCREMENT,
  `precioTotal` VARCHAR(45) NULL,
  `concepto` VARCHAR(45) NULL,
  `fechaliquid` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `tipoPago` VARCHAR(45) NULL,
  `nombrePaciente` INT NOT NULL,
  `servicios_idservicios` INT NOT NULL,
  `impuestos` VARCHAR(45) NULL,
  `subtotal` DOUBLE NULL,
  PRIMARY KEY (`idpagos`, `nombrePaciente`, `servicios_idservicios`),
  INDEX `fk_pagos_pacientes1_idx` (`nombrePaciente` ASC) VISIBLE,
  INDEX `fk_pagos_servicios1_idx` (`servicios_idservicios` ASC) VISIBLE,
  CONSTRAINT `fk_pagos_pacientes1`
    FOREIGN KEY (`nombrePaciente`)
    REFERENCES `mydb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_servicios1`
    FOREIGN KEY (`servicios_idservicios`)
    REFERENCES `mydb`.`servicios` (`idservicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facturacion` (
  `idFacturacion` INT NOT NULL AUTO_INCREMENT,
  `folio` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `consultorios_idconsultorios` INT NOT NULL,
  `pagos_idpagos` INT NOT NULL,
  PRIMARY KEY (`idFacturacion`, `consultorios_idconsultorios`, `pagos_idpagos`),
  INDEX `fk_facturacion_consultorios1_idx` (`consultorios_idconsultorios` ASC) VISIBLE,
  INDEX `fk_facturacion_pagos1_idx` (`pagos_idpagos` ASC) VISIBLE,
  CONSTRAINT `fk_facturacion_consultorios1`
    FOREIGN KEY (`consultorios_idconsultorios`)
    REFERENCES `mydb`.`consultorios` (`idconsultorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturacion_pagos1`
    FOREIGN KEY (`pagos_idpagos`)
    REFERENCES `mydb`.`pagos` (`idpagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
